# Generated by Django 4.1.4 on 2023-03-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phoneno', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('cnfrmpswd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='twowheeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=25)),
                ('vehicle_no', models.CharField(max_length=25)),
                ('vehicleimage', models.ImageField(upload_to='vehicle', verbose_name='Image Thumb')),
                ('rentalprice', models.IntegerField()),
                ('milage', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.CharField(max_length=200)),
                ('startdate', models.CharField(max_length=200)),
                ('returndate', models.CharField(max_length=200)),
                ('bookingpayment', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.twowheeler')),
            ],
        ),
    ]
